### PR TITLE
res: Improved layout to accomodate languages

### PR DESCRIPTION
**Pull request by elluisian**
When applied, this commit should improve the visuals when using languages different from english. There are probably better ways for doing this though

### CODE REVIEW

**Comment by bk138** [comment]
Can you please post before- and after-screenshots?

**Comment by elluisian** [comment]
Yes of course, I admit though that I think there are better ways to... I'm not so sure myself.
The thing is, the current layout values do not accomodate well with languages that use long labels (as the ones I provided).
Here's an example for the french language in comparison to english.

**Comment by elluisian** [comment]
upstream, portrait, english vs french

**Comment by elluisian** [comment]
(Don't mind the Action Bar, it is the effect of the Application Locale Mod lsposed module I'm using to change the language on the go)

Upstream, portrait, English vs French

Screenshot_2024-08-23-12-09-10-442_net christianbeier droidvnc_ng
Screenshot_2024-08-23-12-09-05-927_net christianbeier droidvnc_ng
Screenshot_2024-08-23-12-08-37-877_net christianbeier droidvnc_ng
Screenshot_2024-08-23-12-08-29-346_net christianbeier droidvnc_ng

**Comment by elluisian** [comment]
Upstream, landscape

**English**



**French**

**Comment by elluisian** [comment]
Pull request, portrait

**English**






**French**

**Comment by elluisian** [comment]
Pull request, landscape

**English**








**French**

**Comment by bk138** [comment]
@elluisian I opted for a simpler solution but would not have spotted this with your previous work - thank you!

**Pull request closed without merging**
