### PR TITLE
Revert "MainService: crop image if padding is present"

### PR DESCRIPTION
**Pull request by bk138**
Reverts bk138/droidVNC-NG#127

@eisaev sorry have to revert this, it crashes on my test device. Should've run-tested :roll_eyes: 

```
2023-06-12 09:53:43.555 30343-30343 MainService             net.christianbeier.droidvnc_ng       D  image available
2023-06-12 09:53:43.560 30343-30343 droidvnc-ng (native)    net.christianbeier.droidvnc_ng       E  WARNING: New width (486) is not a multiple of 4.
2023-06-12 09:53:43.560 30343-30343 droidvnc-ng (native)    net.christianbeier.droidvnc_ng       I  vncNewFramebuffer: allocated new framebuffer, 486x1026
2023-06-12 09:53:43.562 30343-30343 libc                    net.christianbeier.droidvnc_ng       A  Fatal signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0x724fe4c000 in tid 30343 (ier.droidvnc_ng), pid 30343 (ier.droidvnc_ng)
2023-06-12 09:53:43.633   976-976   NotificationService     system_server                        E  Muting recently noisy 0|net.christianbeier.droidvnc_ng|11|null|10898
2023-06-12 09:53:43.975 30379-30379 DEBUG                   pid-30379                            A  Cmdline: net.christianbeier.droidvnc_ng
2023-06-12 09:53:43.975 30379-30379 DEBUG                   pid-30379                            A  pid: 30343, tid: 30343, name: ier.droidvnc_ng  >>> net.christianbeier.droidvnc_ng <<<
2023-06-12 09:53:43.976 30379-30379 DEBUG                   pid-30379                            A        #01 pc 0000000000003504  /data/app/~~jJNcXdAKRFcW_Fwm1diAVw==/net.christianbeier.droidvnc_ng-Z9HMSK0TdouY4Q39UQJ94Q==/base.apk!libdroidvnc-ng.so (Java_net_christianbeier_droidvnc_1ng_MainService_vncUpdateFramebuffer+212) (BuildId: c2d812b566d25c1c25b12668e3a8735ada5d287f)
2023-06-12 09:53:43.976 30379-30379 DEBUG                   pid-30379                            A        #09 pc 00000000000061aa  [anon:dalvik-classes3.dex extracted in memory from /data/app/~~jJNcXdAKRFcW_Fwm1diAVw==/net.christianbeier.droidvnc_ng-Z9HMSK0TdouY4Q39UQJ94Q==/base.apk!classes3.dex] (net.christianbeier.droidvnc_ng.MainService.lambda$startScreenCapture$1$net-christianbeier-droidvnc_ng-MainService+198)
2023-06-12 09:53:43.976 30379-30379 DEBUG                   pid-30379                            A        #15 pc 0000000000005a6c  [anon:dalvik-classes3.dex extracted in memory from /data/app/~~jJNcXdAKRFcW_Fwm1diAVw==/net.christianbeier.droidvnc_ng-Z9HMSK0TdouY4Q39UQJ94Q==/base.apk!classes3.dex] (net.christianbeier.droidvnc_ng.MainService$$ExternalSyntheticLambda1.onImageAvailable+16)

```

### CODE REVIEW

**Comment by eisaev** [comment]
@bk138 I see a very unusual screen resolution - 486x1026. Which phone model did you crash on? I will try to reproduce the crash and fix it.

**Comment by eisaev** [comment]
I tried to reproduce the crash on an android emulator with a custom screen resolution (486x1026) with no success.

**Comment by eisaev** [comment]
@bk138 Could you reproduce this crash on debug build and collect a tombstone?

**Comment by bk138** [comment]
I'll have a look ASAP. I think it was a scaled screen on a Galaxy S10.

**Comment by bk138** [comment]
@eisaev Tried with 4c0d5796368dd81c065daa393ae4c82ac58052a0 on a Galaxy S10e w/ scaling set to 60% and got

```
2023-07-29 22:37:13.264  8639-8639  DEBUG                   pid-8639                             A  *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
2023-07-29 22:37:13.264  8639-8639  DEBUG                   pid-8639                             A  Build fingerprint: 'samsung/beyond0lteeea/beyond0:12/SP1A.210812.016/G970FXXSGHWC2:user/release-keys'
2023-07-29 22:37:13.264  8639-8639  DEBUG                   pid-8639                             A  Revision: '26'
2023-07-29 22:37:13.264  8639-8639  DEBUG                   pid-8639                             A  ABI: 'arm64'
2023-07-29 22:37:13.264  8639-8639  DEBUG                   pid-8639                             A  Processor: '5'
2023-07-29 22:37:13.264  8639-8639  DEBUG                   pid-8639                             A  Timestamp: 2023-07-29 22:37:12.997128838+0200
2023-07-29 22:37:13.264  8639-8639  DEBUG                   pid-8639                             A  Process uptime: 2s
2023-07-29 22:37:13.264  8639-8639  DEBUG                   pid-8639                             A  Cmdline: net.christianbeier.droidvnc_ng
2023-07-29 22:37:13.264  8639-8639  DEBUG                   pid-8639                             A  pid: 8597, tid: 8597, name: ier.droidvnc_ng  >>> net.christianbeier.droidvnc_ng <<<
2023-07-29 22:37:13.264  8639-8639  DEBUG                   pid-8639                             A  uid: 10934
2023-07-29 22:37:13.264  8639-8639  DEBUG                   pid-8639                             A  signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0x766fcfa000
2023-07-29 22:37:13.264  8639-8639  DEBUG                   pid-8639                             A      x0  000000766f998500  x1  0000007670aa1b00  x2  000000000000aab0  x3  000000766fcf9fc0
2023-07-29 22:37:13.264  8639-8639  DEBUG                   pid-8639                             A      x4  0000007670aac600  x5  000000766fd04b00  x6  ff251c1aff241b19  x7  ff261d1cff251c1a
2023-07-29 22:37:13.264  8639-8639  DEBUG                   pid-8639                             A      x8  ff261d1cff261d1c  x9  ff251e1cff251e1c  x10 ff241c1bff251e1c  x11 ff231c1aff241c1b
2023-07-29 22:37:13.264  8639-8639  DEBUG                   pid-8639                             A      x12 ff231a18ff231a17  x13 ff241b19ff231a18  x14 00357a7a23826afe  x15 000060a16139ead8
2023-07-29 22:37:13.264  8639-8639  DEBUG                   pid-8639                             A      x16 00000079de1fdf10  x17 00000079de187ef0  x18 0000007a05702000  x19 000000785a2197b0
2023-07-29 22:37:13.264  8639-8639  DEBUG                   pid-8639                             A      x20 0000000000000000  x21 000000785a2197b0  x22 0000007a05094000  x23 000000785a219860
2023-07-29 22:37:13.264  8639-8639  DEBUG                   pid-8639                             A      x24 00000076d2a32fd8  x25 00000077ca21aeb0  x26 0000007a05094000  x27 000000000000009b
2023-07-29 22:37:13.264  8639-8639  DEBUG                   pid-8639                             A      x28 0000007ff4d07960  x29 0000007ff4d07940
2023-07-29 22:37:13.264  8639-8639  DEBUG                   pid-8639                             A      lr  00000076d0552508  sp  0000007ff4d078e0  pc  00000079de187ea8  pst 0000000020000000
2023-07-29 22:37:13.264  8639-8639  DEBUG                   pid-8639                             A  backtrace:
2023-07-29 22:37:13.264  8639-8639  DEBUG                   pid-8639                             A        #00 pc 000000000004cea8  /apex/com.android.runtime/lib64/bionic/libc.so (__memcpy+296) (BuildId: 88b933fc529619f5e58bc6d5510017ee)
2023-07-29 22:37:13.264  8639-8639  DEBUG                   pid-8639                             A        #01 pc 0000000000003504  /data/app/~~PwrdBRLkp5gvTXpyMX2H4Q==/net.christianbeier.droidvnc_ng-u3kw4oeBKwj6_8K23sZ0Zw==/base.apk!libdroidvnc-ng.so (Java_net_christianbeier_droidvnc_1ng_MainService_vncUpdateFramebuffer+212) (BuildId: c2d812b566d25c1c25b12668e3a8735ada5d287f)
2023-07-29 22:37:13.264  8639-8639  DEBUG                   pid-8639                             A        #02 pc 0000000000222244  /apex/com.android.art/lib64/libart.so (art_quick_generic_jni_trampoline+148) (BuildId: 1724d2edb620afb8c3e8c5ea6c61ac19)
2023-07-29 22:37:13.264  8639-8639  DEBUG                   pid-8639                             A        #03 pc 0000000000218964  /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+548) (BuildId: 1724d2edb620afb8c3e8c5ea6c61ac19)
2023-07-29 22:37:13.264  8639-8639  DEBUG                   pid-8639                             A        #04 pc 00000000002851f0  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+184) (BuildId: 1724d2edb620afb8c3e8c5ea6c61ac19)
2023-07-29 22:37:13.264  8639-8639  DEBUG                   pid-8639                             A        #05 pc 00000000003e70f0  /apex/com.android.art/lib64/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+400) (BuildId: 1724d2edb620afb8c3e8c5ea6c61ac19)
2023-07-29 22:37:13.264  8639-8639  DEBUG                   pid-8639                             A        #06 pc 00000000003e1cec  /apex/com.android.art/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+804) (BuildId: 1724d2edb620afb8c3e8c5ea6c61ac19)
2023-07-29 22:37:13.264  8639-8639  DEBUG                   pid-8639                             A        #07 pc 0000000000761094  /apex/com.android.art/lib64/libart.so (MterpInvokeDirect+1036) (BuildId: 1724d2edb620afb8c3e8c5ea6c61ac19)
2023-07-29 22:37:13.264  8639-8639  DEBUG                   pid-8639                             A        #08 pc 0000000000203914  /apex/com.android.art/lib64/libart.so (mterp_op_invoke_direct+20) (BuildId: 1724d2edb620afb8c3e8c5ea6c61ac19)
2023-07-29 22:37:13.264  8639-8639  DEBUG                   pid-8639                             A        #09 pc 0000000000aac53e  /data/app/~~PwrdBRLkp5gvTXpyMX2H4Q==/net.christianbeier.droidvnc_ng-u3kw4oeBKwj6_8K23sZ0Zw==/oat/arm64/base.vdex (net.christianbeier.droidvnc_ng.MainService.lambda$startScreenCapture$1$net-christianbeier-droidvnc_ng-MainService+198)
2023-07-29 22:37:13.264  8639-8639  DEBUG                   pid-8639                             A        #10 pc 00000000003d98e0  /apex/com.android.art/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool, bool)+304) (BuildId: 1724d2edb620afb8c3e8c5ea6c61ac19)
2023-07-29 22:37:13.264  8639-8639  DEBUG                   pid-8639                             A        #11 pc 00000000003e1254  /apex/com.android.art/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+204) (BuildId: 1724d2edb620afb8c3e8c5ea6c61ac19)
2023-07-29 22:37:13.265  8639-8639  DEBUG                   pid-8639                             A        #12 pc 00000000003e1cc8  /apex/com.android.art/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+768) (BuildId: 1724d2edb620afb8c3e8c5ea6c61ac19)
2023-07-29 22:37:13.265  8639-8639  DEBUG                   pid-8639                             A        #13 pc 0000000000757d64  /apex/com.android.art/lib64/libart.so (MterpInvokeVirtual+1164) (BuildId: 1724d2edb620afb8c3e8c5ea6c61ac19)
2023-07-29 22:37:13.265  8639-8639  DEBUG                   pid-8639                             A        #14 pc 0000000000203814  /apex/com.android.art/lib64/libart.so (mterp_op_invoke_virtual+20) (BuildId: 1724d2edb620afb8c3e8c5ea6c61ac19)
2023-07-29 22:37:13.265  8639-8639  DEBUG                   pid-8639                             A        #15 pc 0000000000aabec8  /data/app/~~PwrdBRLkp5gvTXpyMX2H4Q==/net.christianbeier.droidvnc_ng-u3kw4oeBKwj6_8K23sZ0Zw==/oat/arm64/base.vdex (net.christianbeier.droidvnc_ng.MainService$$ExternalSyntheticLambda1.onImageAvailable+16)
2023-07-29 22:37:13.265  8639-8639  DEBUG                   pid-8639                             A        #16 pc 00000000003d98e0  /apex/com.android.art/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool, bool)+304) (BuildId: 1724d2edb620afb8c3e8c5ea6c61ac19)
2023-07-29 22:37:13.265  8639-8639  DEBUG                   pid-8639                             A        #17 pc 00000000003e1254  /apex/com.android.art/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+204) (BuildId: 1724d2edb620afb8c3e8c5ea6c61ac19)
2023-07-29 22:37:13.265  8639-8639  DEBUG                   pid-8639                             A        #18 pc 00000000003e1cc8  /apex/com.android.art/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+768) (BuildId: 1724d2edb620afb8c3e8c5ea6c61ac19)
2023-07-29 22:37:13.265  8639-8639  DEBUG                   pid-8639                             A        #19 pc 000000000075dfe0  /apex/com.android.art/lib64/libart.so (MterpInvokeInterface+1568) (BuildId: 1724d2edb620afb8c3e8c5ea6c61ac19)
2023-07-29 22:37:13.265  8639-8639  DEBUG                   pid-8639                             A        #20 pc 0000000000203a14  /apex/com.android.art/lib64/libart.so (mterp_op_invoke_interface+20) (BuildId: 1724d2edb620afb8c3e8c5ea6c61ac19)
2023-07-29 22:37:13.265  8639-8639  DEBUG                   pid-8639                             A        #21 pc 000000000034be14  /system/framework/framework.jar (android.media.ImageReader$1.run+8)
2023-07-29 22:37:13.265  8639-8639  DEBUG                   pid-8639                             A        #22 pc 00000000003d98e0  /apex/com.android.art/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool, bool)+304) (BuildId: 1724d2edb620afb8c3e8c5ea6c61ac19)
2023-07-29 22:37:13.265  8639-8639  DEBUG                   pid-8639                             A        #23 pc 00000000003e1254  /apex/com.android.art/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+204) (BuildId: 1724d2edb620afb8c3e8c5ea6c61ac19)
2023-07-29 22:37:13.265  8639-8639  DEBUG                   pid-8639                             A        #24 pc 00000000003e1cc8  /apex/com.android.art/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+768) (BuildId: 1724d2edb620afb8c3e8c5ea6c61ac19)
2023-07-29 22:37:13.265  8639-8639  DEBUG                   pid-8639                             A        #25 pc 000000000075dfe0  /apex/com.android.art/lib64/libart.so (MterpInvokeInterface+1568) (BuildId: 1724d2edb620afb8c3e8c5ea6c61ac19)
2023-07-29 22:37:13.265  8639-8639  DEBUG                   pid-8639                             A        #26 pc 0000000000203a14  /apex/com.android.art/lib64/libart.so (mterp_op_invoke_interface+20) (BuildId: 1724d2edb620afb8c3e8c5ea6c61ac19)
2023-07-29 22:37:13.265  8639-8639  DEBUG                   pid-8639                             A        #27 pc 000000000048dcfc  /system/framework/framework.jar (android.os.Handler.handleCallback+4)
2023-07-29 22:37:13.265  8639-8639  DEBUG                   pid-8639                             A        #28 pc 0000000000763268  /apex/com.android.art/lib64/libart.so (MterpInvokeStatic+2152) (BuildId: 1724d2edb620afb8c3e8c5ea6c61ac19)
2023-07-29 22:37:13.265  8639-8639  DEBUG                   pid-8639                             A        #29 pc 0000000000203994  /apex/com.android.art/lib64/libart.so (mterp_op_invoke_static+20) (BuildId: 1724d2edb620afb8c3e8c5ea6c61ac19)
2023-07-29 22:37:13.265  8639-8639  DEBUG                   pid-8639                             A        #30 pc 000000000048db70  /system/framework/framework.jar (android.os.Handler.dispatchMessage+8)
2023-07-29 22:37:13.265  8639-8639  DEBUG                   pid-8639                             A        #31 pc 00000000007584b4  /apex/com.android.art/lib64/libart.so (MterpInvokeVirtual+3036) (BuildId: 1724d2edb620afb8c3e8c5ea6c61ac19)
2023-07-29 22:37:13.265  8639-8639  DEBUG                   pid-8639                             A        #32 pc 0000000000203814  /apex/com.android.art/lib64/libart.so (mterp_op_invoke_virtual+20) (BuildId: 1724d2edb620afb8c3e8c5ea6c61ac19)
2023-07-29 22:37:13.265  8639-8639  DEBUG                   pid-8639                             A        #33 pc 00000000004cb102  /system/framework/framework.jar (android.os.Looper.loopOnce+334)
2023-07-29 22:37:13.265  8639-8639  DEBUG                   pid-8639                             A        #34 pc 0000000000763268  /apex/com.android.art/lib64/libart.so (MterpInvokeStatic+2152) (BuildId: 1724d2edb620afb8c3e8c5ea6c61ac19)
2023-07-29 22:37:13.265  8639-8639  DEBUG                   pid-8639                             A        #35 pc 0000000000203994  /apex/com.android.art/lib64/libart.so (mterp_op_invoke_static+20) (BuildId: 1724d2edb620afb8c3e8c5ea6c61ac19)
2023-07-29 22:37:13.265  8639-8639  DEBUG                   pid-8639                             A        #36 pc 00000000004cb7f8  /system/framework/framework.jar (android.os.Looper.loop+152)
2023-07-29 22:37:13.265  8639-8639  DEBUG                   pid-8639                             A        #37 pc 0000000000763330  /apex/com.android.art/lib64/libart.so (MterpInvokeStatic+2352) (BuildId: 1724d2edb620afb8c3e8c5ea6c61ac19)
2023-07-29 22:37:13.265  8639-8639  DEBUG                   pid-8639                             A        #38 pc 0000000000203994  /apex/com.android.art/lib64/libart.so (mterp_op_invoke_static+20) (BuildId: 1724d2edb620afb8c3e8c5ea6c61ac19)
2023-07-29 22:37:13.265  8639-8639  DEBUG                   pid-8639                             A        #39 pc 00000000001bd1e2  /system/framework/framework.jar (android.app.ActivityThread.main+214)
2023-07-29 22:37:13.265  8639-8639  DEBUG                   pid-8639                             A        #40 pc 00000000003d98e0  /apex/com.android.art/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool, bool)+304) (BuildId: 1724d2edb620afb8c3e8c5ea6c61ac19)
2023-07-29 22:37:13.265  8639-8639  DEBUG                   pid-8639                             A        #41 pc 000000000074657c  /apex/com.android.art/lib64/libart.so (artQuickToInterpreterBridge+780) (BuildId: 1724d2edb620afb8c3e8c5ea6c61ac19)
2023-07-29 22:37:13.265  8639-8639  DEBUG                   pid-8639                             A        #42 pc 0000000000222378  /apex/com.android.art/lib64/libart.so (art_quick_to_interpreter_bridge+88) (BuildId: 1724d2edb620afb8c3e8c5ea6c61ac19)
2023-07-29 22:37:13.265  8639-8639  DEBUG                   pid-8639                             A        #43 pc 0000000000218be8  /apex/com.android.art/lib64/libart.so (art_quick_invoke_static_stub+568) (BuildId: 1724d2edb620afb8c3e8c5ea6c61ac19)
2023-07-29 22:37:13.265  8639-8639  DEBUG                   pid-8639                             A        #44 pc 000000000028520c  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+212) (BuildId: 1724d2edb620afb8c3e8c5ea6c61ac19)
2023-07-29 22:37:13.265  8639-8639  DEBUG                   pid-8639                             A        #45 pc 0000000000627760  /apex/com.android.art/lib64/libart.so (_jobject* art::InvokeMethod<(art::PointerSize)8>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jobject*, _jobject*, unsigned long)+1384) (BuildId: 1724d2edb620afb8c3e8c5ea6c61ac19)
2023-07-29 22:37:13.265  8639-8639  DEBUG                   pid-8639                             A        #46 pc 0000000000597a38  /apex/com.android.art/lib64/libart.so (art::Method_invoke(_JNIEnv*, _jobject*, _jobject*, _jobjectArray*)+48) (BuildId: 1724d2edb620afb8c3e8c5ea6c61ac19)
2023-07-29 22:37:13.265  8639-8639  DEBUG                   pid-8639                             A        #47 pc 00000000000b2f74  /apex/com.android.art/javalib/arm64/boot.oat (art_jni_trampoline+132) (BuildId: f35585e93c1ff4c865b6334fa014e97244124284)
2023-07-29 22:37:13.265  8639-8639  DEBUG                   pid-8639                             A        #48 pc 0000000000218964  /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+548) (BuildId: 1724d2edb620afb8c3e8c5ea6c61ac19)
2023-07-29 22:37:13.265  8639-8639  DEBUG                   pid-8639                             A        #49 pc 00000000002851f0  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+184) (BuildId: 1724d2edb620afb8c3e8c5ea6c61ac19)
2023-07-29 22:37:13.265  8639-8639  DEBUG                   pid-8639                             A        #50 pc 00000000003e70f0  /apex/com.android.art/lib64/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+400) (BuildId: 1724d2edb620afb8c3e8c5ea6c61ac19)
2023-07-29 22:37:13.265  8639-8639  DEBUG                   pid-8639                             A        #51 pc 00000000003e1cec  /apex/com.android.art/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+804) (BuildId: 1724d2edb620afb8c3e8c5ea6c61ac19)
2023-07-29 22:37:13.265  8639-8639  DEBUG                   pid-8639                             A        #52 pc 0000000000757d64  /apex/com.android.art/lib64/libart.so (MterpInvokeVirtual+1164) (BuildId: 1724d2edb620afb8c3e8c5ea6c61ac19)
2023-07-29 22:37:13.265  8639-8639  DEBUG                   pid-8639                             A        #53 pc 0000000000203814  /apex/com.android.art/lib64/libart.so (mterp_op_invoke_virtual+20) (BuildId: 1724d2edb620afb8c3e8c5ea6c61ac19)
2023-07-29 22:37:13.265  8639-8639  DEBUG                   pid-8639                             A        #54 pc 000000000045ae52  /system/framework/framework.jar (com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run+22)
2023-07-29 22:37:13.265  8639-8639  DEBUG                   pid-8639                             A        #55 pc 00000000003d98e0  /apex/com.android.art/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool, bool)+304) (BuildId: 1724d2edb620afb8c3e8c5ea6c61ac19)
2023-07-29 22:37:13.265  8639-8639  DEBUG                   pid-8639                             A        #56 pc 000000000074657c  /apex/com.android.art/lib64/libart.so (artQuickToInterpreterBridge+780) (BuildId: 1724d2edb620afb8c3e8c5ea6c61ac19)
2023-07-29 22:37:13.265  8639-8639  DEBUG                   pid-8639                             A        #57 pc 0000000000222378  /apex/com.android.art/lib64/libart.so (art_quick_to_interpreter_bridge+88) (BuildId: 1724d2edb620afb8c3e8c5ea6c61ac19)
2023-07-29 22:37:13.265  8639-8639  DEBUG                   pid-8639                             A        #58 pc 0000000000aec438  /system/framework/arm64/boot-framework.oat (com.android.internal.os.ZygoteInit.main+2376) (BuildId: 6c25cb524d5442a9ac8e161887c22e9bcc316274)
2023-07-29 22:37:13.265  8639-8639  DEBUG                   pid-8639                             A        #59 pc 0000000000218be8  /apex/com.android.art/lib64/libart.so (art_quick_invoke_static_stub+568) (BuildId: 1724d2edb620afb8c3e8c5ea6c61ac19)
2023-07-29 22:37:13.265  8639-8639  DEBUG                   pid-8639                             A        #60 pc 000000000028520c  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+212) (BuildId: 1724d2edb620afb8c3e8c5ea6c61ac19)
2023-07-29 22:37:13.265  8639-8639  DEBUG                   pid-8639                             A        #61 pc 0000000000627ec0  /apex/com.android.art/lib64/libart.so (art::JValue art::InvokeWithVarArgs<art::ArtMethod*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, art::ArtMethod*, std::__va_list)+448) (BuildId: 1724d2edb620afb8c3e8c5ea6c61ac19)
2023-07-29 22:37:13.265  8639-8639  DEBUG                   pid-8639                             A        #62 pc 0000000000628394  /apex/com.android.art/lib64/libart.so (art::JValue art::InvokeWithVarArgs<_jmethodID*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, std::__va_list)+92) (BuildId: 1724d2edb620afb8c3e8c5ea6c61ac19)
2023-07-29 22:37:13.265  8639-8639  DEBUG                   pid-8639                             A        #63 pc 0000000000501094  /apex/com.android.art/lib64/libart.so (art::JNI<true>::CallStaticVoidMethodV(_JNIEnv*, _jclass*, _jmethodID*, std::__va_list)+612) (BuildId: 1724d2edb620afb8c3e8c5ea6c61ac19)
2023-07-29 22:37:13.265  8639-8639  DEBUG                   pid-8639                             A        #64 pc 00000000000b2b28  /system/lib64/libandroid_runtime.so (_JNIEnv::CallStaticVoidMethod(_jclass*, _jmethodID*, ...)+120) (BuildId: 4fc19597c49370ff496a612342e7623c)
2023-07-29 22:37:13.265  8639-8639  DEBUG                   pid-8639                             A        #65 pc 00000000000becd8  /system/lib64/libandroid_runtime.so (android::AndroidRuntime::start(char const*, android::Vector<android::String8> const&, bool)+856) (BuildId: 4fc19597c49370ff496a612342e7623c)
2023-07-29 22:37:13.265  8639-8639  DEBUG                   pid-8639                             A        #66 pc 00000000000025b0  /system/bin/app_process64 (main+1368) (BuildId: 9a7b5029aaf92752a6307785aa874b5a)
2023-07-29 22:37:13.265  8639-8639  DEBUG                   pid-8639                             A        #67 pc 0000000000049b48  /apex/com.android.runtime/lib64/bionic/libc.so (__libc_init+96) (BuildId: 88b933fc529619f5e58bc6d5510017ee)
2023-07-29 22:37:13.295   501-501   tombstoned              tombstoned                           E  Tombstone written to: tombstone_22
```

**Comment by eisaev** [comment]
Thanks! It looks like the crash happened here:
https://github.com/bk138/droidVNC-NG/blob/4c0d5796368dd81c065daa393ae4c82ac58052a0/app/src/main/cpp/droidvnc-ng.c#L441
```cpp
JNIEXPORT jboolean JNICALL Java_net_christianbeier_droidvnc_1ng_MainService_vncUpdateFramebuffer(JNIEnv *env, jobject  __unused thiz, jobject buf)
{
    void *cBuf = (*env)->GetDirectBufferAddress(env, buf);
    jlong bufSize = (*env)->GetDirectBufferCapacity(env, buf);

    if(!theScreen || !theScreen->frameBuffer || !cBuf || bufSize < 0)
        return JNI_FALSE;

    double t0 = getTime();
    memcpy(theScreen->frameBuffer, cBuf, bufSize);  <<<<<<<<<<<<< crash <<<<<<<<<<<<<
    __android_log_print(ANDROID_LOG_DEBUG, TAG, "vncUpdateFramebuffer: copy took %.3f ms", (getTime()-t0)*1000);

    rfbMarkRectAsModified(theScreen, 0, 0, theScreen->width, theScreen->height);

    return JNI_TRUE;
}
```
> Galaxy S10e w/ scaling set to 60%
Do you mean `Settings`->`Display`->`Screen zoom`? I have Galaxy A52 and there is nothing related to screen scaling.

**Comment by bk138** [comment]
Just an idea, maybe its simpler to just declare the black stripes pixels transparent? Dont know if viewers support this...

**Comment by eisaev** [comment]
> can't seem to access /data/tombstones/tombstone_22 on this device...
You can use `adb bugreport` to collect tombstones.

**Comment by eisaev** [comment]
> I reproduced the crash on my phone.

I made premature conclusions, because I couldn't reproduce the crash.

**Comment by eisaev** [comment]
Could you reproduce crash with this patch:
```

**Comment by eisaev** [comment]
Could you reproduce crash with this patch?
```
diff --git a/app/src/main/cpp/droidvnc-ng.c b/app/src/main/cpp/droidvnc-ng.c
index 334ef06..89dc292 100644
--- a/app/src/main/cpp/droidvnc-ng.c
+++ b/app/src/main/cpp/droidvnc-ng.c
@@ -415,6 +415,7 @@ JNIEXPORT jboolean JNICALL Java_net_christianbeier_droidvnc_1ng_MainService_vncN
         return JNI_FALSE;

     oldfb = theScreen->frameBuffer;
+    __android_log_print(ANDROID_LOG_DEBUG, TAG, "eisaev: width * height * 4=%d", width * height * 4);
     newfb = calloc(width * height * 4, 1);
     if(!newfb) {
         __android_log_print(ANDROID_LOG_ERROR, TAG, "vncNewFramebuffer: failed allocating new framebuffer");
@@ -438,6 +439,7 @@ JNIEXPORT jboolean JNICALL Java_net_christianbeier_droidvnc_1ng_MainService_vncU
         return JNI_FALSE;

     double t0 = getTime();
+    __android_log_print(ANDROID_LOG_DEBUG, TAG, "eisaev: bufSize=%d", bufSize);
     memcpy(theScreen->frameBuffer, cBuf, bufSize);
     __android_log_print(ANDROID_LOG_DEBUG, TAG, "vncUpdateFramebuffer: copy took %.3f ms", (getTime()-t0)*1000);

```
It would be very helpful if you collect logcat data and tombstone (try the 'adb bugreport` command)

**Comment by eisaev** [comment]
@bk138 I think I fixed this issue in the branch [eisaev/crop-padding_2](https://github.com/eisaev/droidVNC-NG/tree/eisaev/crop-padding_2). Please confirm when you have time to test on the problem phone. If it's fixed, I will prepare a new pull request.

**Pull request merged**
