### PR TITLE
update：add Chinese-Simplified

### PR DESCRIPTION
**Pull request by greatyingzi**
strip so;
upgrade kotlin to 1.8.0

### CODE REVIEW

**Comment by bk138** [comment]
Thanks for the contribution. Please split the changes into several PRs or at least several commits. What are the buildsystem changes about?

**Comment by bk138** [comment]
Thanks! Can you translate the rest of the strings as well so the set is complete? That'd be super nice!

**Comment by bk138** [comment]
@greatyingzi Can you finalise the translation?

**Comment by greatyingzi** [comment]
> @greatyingzi Can you finalise the translation?

I can.

**Comment by 1IRang3** [comment]
> strip so;
> upgrade kotlin to 1.8.0

**Comment by bk138** [comment]
> > @greatyingzi Can you finalise the translation?
> 
> I can.

OK, then please go ahead  ;-)

**Comment by greatyingzi** [comment]
> > > @greatyingzi Can you finalise the translation?
> > 
> > 
> > I can.
> 
> OK, then please go ahead ;-)

Done!

**Pull request merged**
